networks:
  cadeiraslusitanasnetwork:

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
          - "8002:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Root123#"

  cadeiraslusitanas:
    container_name: CadeirasLusitanasContainer
    image: ${DOCKER_REGISTRY-}cadeiraslusitanas
    ports:
        - "8001:8080"
    build:
      context: .
      dockerfile: CadeirasLusitanas/Dockerfile
    depends_on:
      - SqlServerDb
