version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=blazorDB;User Id=sa;Password=root;Encrypt=False;Trust Server Certificate=True;


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Root123#"
      ACCEPT_EULA: "Y"
      MSSQL_FORCE_ENCRYPTION: "NO"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
